---
title: "Prosperity for all or prosperity for a few ?"
subtitle: "Empirical evidence of economic inequality in Switzerland"
date: '2025-01-31'
tags: ["Inequality", "Wages", "Productivity", "Poverty", "Switzerland", "Marxism", "Distribution of wealth and income", "Political Economy" ]
header-includes:
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
output:
  html_document:
    df_print: kable
    theme: default
    toc: yes
    toc_depth: 4
    toc_float: yes
    fig_width: 9
    fig_height: 6
    out.width : 60%
  pdf_document:
    toc: yes
    toc_depth: '4'
editor_options:
  
  chunk_output_type: console
---

## Introduction

Switzerland is often hailed as a beacon of prosperity, but a paradox persists: How can a country with such high levels of wealth[^1] also see significant portions of its population at risk of poverty ? This question lies at the heart of the debate over the true nature of prosperity. The mainstream "economy first" approach, while emphasizing economic growth, often overlooks the deeper complexities of wealth distribution and social equality.
Prosperity, as we argue in several of our previous articles[^2], is a multifaceted concept that extends beyond economic measures to include social and political dimensions. Yet, *EconomieSuisse* continues to assert that «both for the national economy as a whole and for each individual, prosperity has increased in Switzerland thanks to solid economic growth »[^3]. From this widely accepted perspective, Switzerland emerges as a land of great wealth, benefiting not only a few but, in theory, everyone. It paints a picture of a “fountain of wealth” where opportunities are abundant for all to partake.

While this narrative may flatter the Swiss ego, it doesn’t hold up under closer scrutiny. When combining poverty rates and at-risk-of-poverty statistics, a different picture of wealth distribution emerges. According to data from the Federal Statistical Office (FSO) presented in **Figure 1** below, poverty, including those at risk of it, rose by nearly 24% between 2013 and 2022. By 2022, around 2 million people were affected by poverty in its broadest sense in the “wealthiest and happiest country” on earth[^4].

<iframe src="/HTML/Fig1_.html" width="100%" height="500" frameborder="0">

</iframe>

If, as Figure 1 demonstrates, poverty indicators challenge the narrative of widespread prosperity, what insights can other measures of economic inequality offer? This article delves into recent trends in wealth inequality, income disparities, and rising exploitation rates in Switzerland. It argues that wealth is intrinsically linked to distributional dynamics, raising critical questions about the fairness of its allocation. Furthermore, the article asserts that relying solely on a single measure of economic inequality overlooks the lived realities of society’s most vulnerable members. Instead, we advocate for a multidimensional approach to deliver a more comprehensive and accurate assessment of the country’s socio-economic challenges.

## The misleading stability in income inequality

Income inequality in Switzerland has traditionally been seen as relatively stable in academic literature[^5]. However, recent studies suggest otherwise, pointing to a gradual but significant increase[^6]. This shift, largely driven by the use of original tax data, aligns with recent economic research, which shows that income inequalities have widened over the past few decades, although not uniformly or with the same intensity[^7].

To illustrate this, **Figure 2** shows the share of total pre-tax income held by the top 10% of earners in Switzerland, Germany, France, Austria, and Great Britain. According to data from the World Inequality Database, Switzerland’s income inequality between the richest 10% and the remaining 90% has remained relatively stable at around 31% between 1980 and 2023. In contrast, income disparities in other major European countries have generally increased.

<iframe src="/HTML/Fig2_.html" width="100%" height="500" frameborder="0">

</iframe>

However, Switzerland’s apparent stability should not be mistaken for success. In fact, the data reveal that, aside from Austria, Switzerland had a higher initial level of inequality at the beginning of the study period. When examining average inequality across the entire period, Switzerland’s income distribution closely mirrors that of its European neighbors. For example, the top 10% of earners in Switzerland hold 31% of the total pre-tax income, compared to 32% in France and 33% in Germany. In this respect, there is no distinct "Sonderfall" for Switzerland.

## Rising exploitation: When productivity outpaces wages

While a 31% share of total income does not imply an equal distribution, the analysis presented so far is not without its criticisms. One key issue lies in the reliance on macroeconomic data, based on national accounts concepts, which can obscure a microeconomics understanding of inequality. From a macroeconomic perspective, focusing on income is certainly informative, but it depoliticizes the issue. In Switzerland, it is wages, not income in its broadest sense, that are subject to negotiation and conflict. Highlighting income inequality may divert attention from the more pressing and actionable discussions surrounding wage disparities.

To complement the income inequality data, **Figure 3** illustrates labor productivity and real wages in Switzerland between 1995 and 2023. Derived from FSO data, these figures show that labor productivity has increased, on average, 2.5 times faster than inflation-adjusted wage growth. In other words, while Swiss workers are increasingly productive, the acceleration in their wages has slowed in comparison to inflation.

<iframe src="/HTML/Fig3_.html" width="100%" height="500" frameborder="0">

</iframe>

In Marxist terms, this dynamic acts as a proxy for the rate of exploitation, i.e the gap between what employees generate and what they actually earn[^8]. ***Figure 4** highlights this gap, particularly during the pandemic period, when the disconnect between productivity and wages widened significantly. This suggests that, during economic crises, the rate of exploitation intensifies, exacerbating the inequality that already exists between the workers' productivity and their compensation.

<iframe src="/HTML/Fig4_.html" width="100%" height="500" frameborder="0">

</iframe>

## Wealth concentration: Switzerland as Europe's top unequal country

Another crucial aspect of economic inequality is wealth distribution. **Figure 5** shows the share of total net wealth held by the top 10% in Switzerland, Germany, France, Austria, and Great Britain. Unlike income inequality, Switzerland has experienced a striking 9% increase in wealth concentration between 1995 and 2022. Notably, almost 63% of Switzerland’s wealth is now held by just 10% of the population, making the country the most unequal among major European nations in terms of wealth distribution over the past decade. This reality seems impossible to reconcile with the assertions of *EconomieSuisse*.

<iframe src="/HTML/Fig5_.html" width="100%" height="500" frameborder="0">

</iframe>

##  Conclusion

In conclusion, while Switzerland is often perceived as a model of prosperity and economic equality, a closer examination of the data presents a more complex and troubling picture. The findings reveal rising inequalities across multiple dimensions, from labor exploitation to wealth concentration. While income inequality may appear stable at first glance, this apparent stability masks an already high level of disparity. Furthermore, the increasing divergence between labor productivity and inflation-adjusted wage growth underscores the growing exploitation of workers, a trend exacerbated during times of economic crisis, such as the pandemic. Finally, Switzerland has emerged as the most unequal of major European nations in terms of wealth distribution, with the top 10% holding an overwhelming share of the country’s wealth.

These observations underscore the importance of adopting a multidimensional approach to better understand socio-economic realities and promote fairer solutions. By moving beyond the conventional, mainstream perspective, we can spark political debates on wealth distribution, wage disparities, and exploitation. This will ultimately pave the way for more equitable policies and a more accurate picture of Switzerland’s economic issues.

[^1]: For a broad discussion of wealth in Switzerland, see our article : https://shadowswisseconomics.com/post/2024-06-21-s-switzerland-truly-wealthy-well-being-and-prosperous/
[^2]:See: https://shadowswisseconomics.com/post/2024-06-21-s-switzerland-truly-wealthy-well-being-and-prosperous/ or https://shadowswisseconomics.com/post/financialization/untitledrmd/
[^3]: https://www.economiesuisse.ch/fr/articles/la-croissance-de-la-suisse-est-elle-avant-tout-quantitative
[^4]: For a caricatured view of Switzerland, see Garçon, F. (2015). La Suisse, pays le plus heureux du monde.  Tallandier.
[^5]: Dell, F., Piketty, T., & Saez, E. (2007). Income and wealth concentration in Switzerland over the twentieth century. Top incomes over the twentieth century: A contrast between continental European and English-speaking countries, 472-500; Grabka, M., & Kuhn, U. (2012). The evolution of income inequality in Germany and Switzerland since the turn of the millennium. SOEPpapers, 464. 
[^6]: Foellmi, R., & Martínez, I. Z. (2017). Volatile top income shares in Switzerland ? Reassessing the evolution between 1981 and 2010. Review of Economics and Statistics, 99(5), 793-809; Foellmi, R., & Martínez, I. Z. (2018). Inequality in Switzerland: A Haven of Stability ?. In CESifo Forum (Vol. 19, No. 2, pp. 19-25). München: ifo Institut-Leibniz-Institut für Wirtschaftsforschung an der Universität München.
[^7]: For a non-exhaustive review, see Piketty, T. (2013). Capital au XXIe Siecle. Editions du Seuil and Piketty, T. (2019). Capital et idéologie. Editions du Seuil.
[^8]: According to Marx, the source of profit in the capitalist mode of production comes from the surplus value produced by the worker. It is the ratio of surplus value to variable capital (wages) that determines the rate of exploitation. One way of measuring this rate is to relate labor productivity to real wages. See : https://wikirouge.net/Taux_de_survaleur


